repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.7.0
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix, "--config=ruff.toml"]
      # Run the formatter.
      - id: ruff-format
        args: ["--config=ruff.toml"]


  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: clippy
        name: clippy-cpu
        args: ['--manifest-path', 'beaker/Cargo.toml', '--fix', '--allow-dirty', '--', '-D', 'warnings', '-D', 'clippy::uninlined_format_args']
      # Format Rust code automatically LAST (after clippy fixes)
      - id: fmt
        args: ['--manifest-path', 'beaker/Cargo.toml', '--']
  # This goes last because formatting may change counts
  - repo: local
    hooks:
      - id: cargo-warloc
        name: Run cargo warloc
        entry: bash scripts/run_warloc.sh
        language: system
        pass_filenames: false
