repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.7.0
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      # Format Rust code automatically
      - id: fmt
        args: ['--manifest-path', 'beaker-rs/Cargo.toml', '--']
      # Run clippy with CPU features (like Linux/Windows CI)
      - id: clippy
        name: clippy-cpu
        args: ['--manifest-path', 'beaker-rs/Cargo.toml', '--features', 'cpu', '--', '-D', 'warnings', '-D', 'clippy::uninlined_format_args']
      # Run clippy with CoreML features (like macOS CI)
      - id: clippy
        name: clippy-coreml
        args: ['--manifest-path', 'beaker-rs/Cargo.toml', '--features', 'coreml', '--', '-D', 'warnings', '-D', 'clippy::uninlined_format_args']
