[project]
name = "bird-head-detector"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.2",
    "pillow>=11.3.0",
    "polars>=1.32.0",
    "tqdm>=4.66.0",
]
