[package]
name = "beaker-stamp"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
directories = "5"

[dev-dependencies]
beaker-stamp-derive = { path = "../beaker-stamp-derive" }
beaker-stamp = { path = "." }
