[package]
name = "beaker"
version = "0.1.0"
edition = "2021"
description = "Detect bird heads in images using YOLOv8 (Rust implementation)"
readme = "README.md"
license = "AGPL-3.0"
repository = "https://github.com/ericphanson/beaker"
authors = ["Eric Hanson"]

[[bin]]
name = "beaker"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
ort = { version = "1.16.3", default-features = false, features = ["load-dynamic"] }
image = { version = "0.25", default-features = false, features = ["png", "jpeg"] }
ndarray = "0.15"
anyhow = "1.0"

[features]
default = ["cpu"]
cpu = []
coreml = ["cpu", "ort/coreml"]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true
