#!/bin/bash
set -euo pipefail

# Ensure the output directory exists
mkdir -p beaker


echo "Generated by \`cargo warloc --by-file\`" > beaker/line_counts.md

# Run the command and append output
cargo warloc --by-file >> beaker/line_counts.md

python3 scripts/summarize.py beaker/line_counts.md
