#!/bin/bash
set -euo pipefail

# Ensure the output directory exists
mkdir -p beaker


echo "Generated by \`cargo warloc --by-file\`" > beaker/line_counts.txt

# Run the command and append output
cargo warloc --by-file >> beaker/line_counts.txt
