#!/bin/bash
set -euo pipefail

# Get the directory of this script, regardless of where it's called from
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
BEAKER_DIR="$PROJECT_ROOT/beaker"
OUTPUT_FILE="$BEAKER_DIR/line_counts.md"
SCRIPT="$SCRIPT_DIR/summarize.py"

# Ensure the output directory exists
mkdir -p "$BEAKER_DIR"

# Write header and run cargo warloc
echo "Generated by \`cargo warloc --by-file\`" > "$OUTPUT_FILE"
cargo warloc --by-file >> "$OUTPUT_FILE"

# Summarize using the Python script
python3 "$SCRIPT" "$OUTPUT_FILE" "$PROJECT_ROOT"
