name: Beaker CI

on:
  push:
    branches: [ main ]
    paths:
      - 'beaker/**'
      - 'beaker-stamp/**'
      - 'beaker-stamp-derive/**'
      - 'Cargo.toml'
      - 'justfile'
      - '.github/workflows/beaker-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'beaker/**'
      - 'beaker-stamp/**'
      - 'beaker-stamp-derive/**'
      - 'Cargo.toml'
      - 'justfile'
      - '.github/workflows/beaker-ci.yml'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: "1"

jobs:
  # Lint job - runs once on Linux only
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "lint"
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Run lint checks
        run: just ci-lint

  # Build and test job - runs on all platforms
  build-test:
    name: Build & Test (${{ matrix.target }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            device: "auto"
          - target: x86_64-apple-darwin
            os: macos-13
            device: "auto"
          - target: aarch64-apple-darwin
            os: macos-latest
            device: "auto"
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            device: "auto"
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install just
        uses: extractions/setup-just@v2

      # sccache for faster compilation
      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.6

      - name: Configure sccache
        shell: bash
        run: |
          echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
          echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
          echo "CMAKE_C_COMPILER_LAUNCHER=sccache" >> $GITHUB_ENV
          echo "CMAKE_CXX_COMPILER_LAUNCHER=sccache" >> $GITHUB_ENV

      # Rust dependency caching
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}
          cache-on-failure: true
          save-if: ${{ github.ref == 'refs/heads/main' }}

      # ONNX model caching
      - name: Cache ONNX models
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/onnx-models
            ~/Library/Caches/onnx-models
            ~\AppData\Local\onnx-models\Cache
          key: onnx-models-v1
          restore-keys: onnx-models-

      - name: Set ONNX cache directory
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            echo "ONNX_MODEL_CACHE_DIR=$HOME/AppData/Local/onnx-models/Cache" >> $GITHUB_ENV
          else
            echo "ONNX_MODEL_CACHE_DIR=$HOME/.cache/onnx-models" >> $GITHUB_ENV
          fi

      # Build release binary only (no debug build)
      - name: Build release
        shell: bash
        run: just build-release ${{ matrix.target }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Show binary information (Unix only, skip Windows for simplicity)
      - name: Show binary info
        if: runner.os != 'Windows'
        run: just build-info ${{ matrix.target }}

      # Pre-download models before running tests
      - name: Preload ONNX models
        shell: bash
        run: just preload-models ${{ matrix.target }} ${{ matrix.device }}

      # Run unit and integration tests
      - name: Run tests
        run: just test ${{ matrix.target }}

      # Run CLI smoke tests
      - name: Test CLI
        shell: bash
        run: |
          just test-cli-help ${{ matrix.target }}
          just test-cli-detect ${{ matrix.target }} ${{ matrix.device }}

      # Platform-specific execution provider tests (only on macOS and Linux)
      - name: Test execution providers
        if: runner.os != 'Windows'
        shell: bash
        run: |
          OS_NAME=$(echo "${{ matrix.os }}" | grep -q "macos" && echo "macos" || echo "linux")
          just test-execution-providers ${{ matrix.target }} $OS_NAME

      # Upload artifacts
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: beaker-${{ matrix.target }}
          path: |
            target/${{ matrix.target }}/release/beaker
            target/${{ matrix.target }}/release/beaker.exe
          retention-days: 7
          if-no-files-found: ignore

      # Show sccache stats
      - name: sccache stats
        shell: bash
        run: sccache --show-stats

  # Summary job
  ci-success:
    name: CI Success
    runs-on: ubuntu-latest
    needs: [lint, build-test]
    if: always()
    steps:
      - name: Check all jobs
        run: |
          if [ "${{ needs.lint.result }}" != "success" ] || [ "${{ needs.build-test.result }}" != "success" ]; then
            echo "Some CI jobs failed"
            exit 1
          fi
          echo "All CI jobs passed!"
