name: Beaker CI

on:
  push:
    branches: [ main ]
    paths:
      - 'beaker/**'
      - '.github/workflows/beaker-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'beaker/**'
      - '.github/workflows/beaker-ci.yml'
  workflow_dispatch:  # Allow manual triggering

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test Beaker
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            device: "auto"  # Will fallback to CPU on Linux
          - target: x86_64-apple-darwin
            os: macos-latest
            device: "auto"  # Will use CoreML on macOS
          - target: aarch64-apple-darwin
            os: macos-latest
            device: "auto"  # Will use CoreML on macOS
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            device: "auto"  # Will fallback to CPU on Windows
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: "beaker -> target"
        # Include ONNX Runtime downloads in cache key
        key: ${{ matrix.target }}-${{ hashFiles('beaker/Cargo.lock') }}-${{ hashFiles('beaker/build.rs') }}

    - name: Cache ONNX model
      uses: actions/cache@v4
      with:
        path: ~/.cache/onnx-models
        key: onnx-model-${{ hashFiles('beaker/build.rs') }}
        restore-keys: |
          onnx-model-
        enableCrossOsArchive: true

    - name: Set model cache environment
      run: echo "ONNX_MODEL_CACHE_DIR=$HOME/.cache/onnx-models" >> $GITHUB_ENV

    - name: Check code formatting
      run: cargo fmt --check
      working-directory: beaker

    - name: Run clippy
      run: cargo clippy --target ${{ matrix.target }} -- -D warnings
      working-directory: beaker

    - name: Build (debug)
      run: cargo build --target ${{ matrix.target }}
      working-directory: beaker

    - name: Build (release)
      run: cargo build --release --target ${{ matrix.target }}
      working-directory: beaker

    - name: Show binary information (Unix)
      if: runner.os != 'Windows'
      run: |
        echo "📊 Binary information:"
        ls -lh target/${{ matrix.target }}/release/beaker
        echo ""
        echo "🔍 Binary size: $(du -h target/${{ matrix.target }}/release/beaker | cut -f1)"
        echo "📏 Stripped size: $(strip target/${{ matrix.target }}/release/beaker -o /tmp/beaker-stripped && du -h /tmp/beaker-stripped | cut -f1)"
      working-directory: beaker

    - name: Show binary information (Windows)
      if: runner.os == 'Windows'
      run: |
        echo "Binary information:"
        Get-ChildItem target/${{ matrix.target }}/release/beaker.exe | Format-Table Name, Length
      working-directory: beaker

    - name: Copy example image to beaker directory
      run: cp example.jpg beaker/

    - name: Test CLI help (Unix)
      if: runner.os != 'Windows'
      run: |
        echo "🧪 Testing CLI help command..."
        ./target/${{ matrix.target }}/release/beaker --help
        echo "✅ CLI help works"
      working-directory: beaker

    - name: Test CLI help (Windows)
      if: runner.os == 'Windows'
      run: |
        echo "Testing CLI help command..."
        ./target/${{ matrix.target }}/release/beaker.exe --help
        echo "CLI help works"
      working-directory: beaker

    - name: Test CLI head detection with ORT logging (Unix)
      if: runner.os != 'Windows'
      env:
        RUST_LOG: "ort=info"
      run: |
        echo "🧪 Testing CLI head detection with ORT logging..."
        echo "Device: ${{ matrix.device }}, Target: ${{ matrix.target }}"
        ./target/${{ matrix.target }}/release/beaker head example.jpg --confidence 0.5 --device ${{ matrix.device }} --metadata
        echo "✅ CLI head detection works"
      working-directory: beaker

    - name: Test CLI head detection with ORT logging (Windows)
      if: runner.os == 'Windows'
      env:
        RUST_LOG: "ort=info"
      run: |
        echo "Testing CLI head detection with ORT logging..."
        echo "Device: ${{ matrix.device }}, Target: ${{ matrix.target }}"
        ./target/${{ matrix.target }}/release/beaker.exe head example.jpg --confidence 0.5 --device ${{ matrix.device }} --metadata
        echo "CLI head detection works"
      working-directory: beaker

    - name: Test execution provider details with debug logging (Unix)
      if: runner.os != 'Windows'
      env:
        RUST_LOG: "ort=debug"
      run: |
        echo "🔍 Testing execution provider details with debug logging..."
        echo "Platform: ${{ matrix.os }}, Target: ${{ matrix.target }}"
        echo "Expected behavior:"
        if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
          echo "  - CoreML should be available and used"
          echo "  - Should see CoreML model compilation logs"
        else
          echo "  - CoreML should not be available, fallback to CPU"
          echo "  - Should see CPU-only execution"
        fi
        echo ""
        echo "=== Running with --device auto ==="
        ./target/${{ matrix.target }}/release/beaker head example.jpg --confidence 0.5 --device auto --metadata
        echo ""
        echo "=== Running with --device cpu ==="
        ./target/${{ matrix.target }}/release/beaker head example.jpg --confidence 0.5 --device cpu --metadata
        echo "✅ Execution provider testing complete"
      working-directory: beaker

    - name: Test execution provider details with debug logging (Windows)
      if: runner.os == 'Windows'
      env:
        RUST_LOG: "ort=debug"
      run: |
        echo "Testing execution provider details with debug logging..."
        echo "Platform: ${{ matrix.os }}, Target: ${{ matrix.target }}"
        echo "Expected: CoreML should not be available, fallback to CPU"
        echo ""
        echo "=== Running with --device auto ==="
        ./target/${{ matrix.target }}/release/beaker.exe head example.jpg --confidence 0.5 --device auto --metadata
        echo ""
        echo "=== Running with --device cpu ==="
        ./target/${{ matrix.target }}/release/beaker.exe head example.jpg --confidence 0.5 --device cpu --metadata
        echo "Execution provider testing complete"
      working-directory: beaker

    - name: Copy second test image
      run: cp example-2-birds.jpg beaker/

    - name: Run integration tests
      env:
        RUST_LOG: "warn"  # Reduce log noise for tests
      run: cargo test --release --target ${{ matrix.target }}
      working-directory: beaker

    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: beaker-${{ matrix.target }}
        path: |
          beaker/target/${{ matrix.target }}/release/beaker*
        retention-days: 7



  # Cross-compilation disabled due to ONNX Runtime complexity
  # Use native runners for each target instead
  # Static musl builds disabled due to ONNX Runtime linking complexity

  # Summary job that depends on all others
  rust-ci-success:
    name: Rust CI Success
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - name: Mark as successful
      run: echo "🎉 All Rust CI jobs completed successfully!"
