name: Test Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]
        exclude:
          # Skip some combinations to reduce CI load
          - os: windows-latest
            python-version: "3.10"
          - os: windows-latest
            python-version: "3.11"

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Install dependencies
      run: uv sync --all-extras

    - name: Build package
      run: uv build

    - name: Run end-to-end tests
      run: uv run python test/run_tests.py

    - name: Test tool installation (Unix)
      if: runner.os != 'Windows'
      run: |
        echo "🧪 Testing uv tool install..."
        uv tool install .
        echo "✅ Tool installed successfully"

        echo "🧪 Testing tool execution..."
        bird-head-detector --help
        echo "✅ Tool help command works"

        echo "🧪 Testing tool uninstall..."
        uv tool uninstall bird-head-detector
        echo "✅ Tool uninstalled successfully"

    - name: Test tool installation (Windows)
      if: runner.os == 'Windows'
      shell: cmd
      run: |
        echo Testing uv tool install...
        uv tool install .
        echo Tool installed successfully

        echo Testing tool execution...
        bird-head-detector --help
        echo Tool help command works

        echo Testing tool uninstall...
        uv tool uninstall bird-head-detector
        echo Tool uninstalled successfully

    - name: Upload test artifacts on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-debug-artifacts-${{ matrix.os }}-python${{ matrix.python-version }}
        path: |
          test/
          ./**/*.log
        retention-days: 7

  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Set up Python
      run: uv python install 3.12

    - name: Install dependencies
      run: uv sync --all-extras

    - name: Run ruff check
      run: uv run ruff check .

    - name: Run ruff format check
      run: uv run ruff format --check .

  security:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Set up Python
      run: uv python install 3.12

    - name: Install dependencies
      run: uv sync --all-extras

    - name: Run security audit
      run: |
        echo "🔍 Running security audit..."
        uv run pip-audit --desc --ignore-vuln GHSA-887c-mr87-cxwp || {
          echo "⚠️  Security audit completed with warnings (expected for local packages and non-applicable vulnerabilities)"
          exit 0
        }
