name: Comprehensive Test Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]
        exclude:
          # Skip some combinations to reduce CI load
          - os: windows-latest
            python-version: "3.10"
          - os: windows-latest  
            python-version: "3.11"
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
        
    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}
      
    - name: Install dependencies
      run: uv sync --all-extras
      
    - name: Build package
      run: uv build
      
    - name: Verify package contents
      shell: bash
      run: |
        echo "📦 Built package contents:"
        ls -la dist/
        echo ""
        echo "🔍 Package metadata:"
        uv run python -c "
        import bird_head_detector
        print(f'Version: {bird_head_detector.__version__}')
        print(f'Module path: {bird_head_detector.__file__}')
        "
      
    - name: Run end-to-end tests
      run: uv run python test/run_tests.py
      
    - name: Test tool installation (Unix)
      if: runner.os != 'Windows'
      run: |
        echo "🧪 Testing uv tool install..."
        uv tool install .
        echo "✅ Tool installed successfully"
        
        echo "🧪 Testing tool execution..."
        bird-head-detector --help
        echo "✅ Tool help command works"
        
        echo "🧪 Testing tool uninstall..."
        uv tool uninstall bird-head-detector
        echo "✅ Tool uninstalled successfully"
        
    - name: Test tool installation (Windows)
      if: runner.os == 'Windows'
      shell: cmd
      run: |
        echo Testing uv tool install...
        uv tool install .
        echo Tool installed successfully
        
        echo Testing tool execution...
        bird-head-detector --help
        echo Tool help command works
        
        echo Testing tool uninstall...
        uv tool uninstall bird-head-detector
        echo Tool uninstalled successfully
      
    - name: Upload test artifacts on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-debug-artifacts-${{ matrix.os }}-python${{ matrix.python-version }}
        path: |
          test/
          dist/
          ./**/*.log
        retention-days: 7
        
    - name: Upload build artifacts
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.12'
      uses: actions/upload-artifact@v4
      with:
        name: dist-packages
        path: dist/
        retention-days: 30

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
        
    - name: Set up Python
      run: uv python install 3.12
      
    - name: Install dependencies
      run: uv sync --all-extras
      
    - name: Run ruff check
      run: uv run ruff check .
      
    - name: Run ruff format check
      run: uv run ruff format --check .

  security:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
        
    - name: Set up Python
      run: uv python install 3.12
      
    - name: Install dependencies
      run: uv sync --all-extras
      
    - name: Install security tools
      run: uv pip install pip-audit
      
    - name: Run security audit
      run: uv run pip-audit --desc || echo "Security audit completed with warnings"
