[target.x86_64-unknown-linux-gnu]
rustflags = ["-Clink-args=-Wl,-rpath,$ORIGIN"]

[target.x86_64-unknown-linux-musl]
rustflags = ["-Clink-args=-Wl,-rpath,$ORIGIN"]

[target.x86_64-pc-windows-msvc]
# Windows uses different library loading mechanism, handled by ort

[target.x86_64-apple-darwin]
rustflags = ["-Clink-args=-Wl,-rpath,@loader_path"]

[target.aarch64-apple-darwin]
rustflags = ["-Clink-args=-Wl,-rpath,@loader_path"]
