[project]
name = "pose-model"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "~=3.11"
dependencies = [
    "pyyaml>=6.0.2",
    "timm>=1.0.19",
    "torch>=2.7.1",
]
